site_name: Cyber-Physical Systems

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.breadcrumbs
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
      #- toc.integrate
  nav_dpeth: 4
  palette:
    scheme: slate
    primary: blue-grey
    accent: cyan

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Notes: 
    - 'Module 0 - Introduction': notes/Module0.md
    - 'Module 1 - Computational Systems': notes/Module1.md
    - 'Module 2 - Computer Architecture and Programming Languages': notes/Module2.md
    - 'Module 3 - Wired Communication Protocols': notes/Module3.md
    - 'Module 4 - Wireless Communication Protocols': notes/Module4.md
    - 'Module 5 - Communication Networks': notes/Module5.md
    - 'Module 6 - Actuators': notes/Module6.md
    - 'Module 7 - Sensors': notes/Module7.md
    - 'Module 8 - Systems of Sensors and Actuators': notes/Module8.md
    - 'Module 9 - State Estimation': notes/Module9.md
  - Lecture Slides: pages/LectureSlides.md
  - Labs:
    - 'Lab 0 - Programming Languages': labs/Lab0/Lab0.md
    - 'Lab 1 - Wired Communication Protocols': labs/Lab1/Lab1.md
    - 'Lab 2 - Wireless Communication Protocols': labs/Lab2/Lab2.md
  - Case Studies:
    - 'Case Study 1 - Traffic Light Cameras': case_studies/RedLightCameraNIST.md
  - Tutorials:
    - 'Introduction to Raspberry Pi Zero': tutorials/zero_tutorial.md
    - 'Raspberry Pi Zero Wifi Setup': tutorials/zero_wifi.md
    - 'Asynchronous Programming': tutorials/async_tutorial.md
    - 'Lab Report Writing': pages/rubric.md